name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@alpha.1.0.0

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@alpha.1.0.0
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/var/www/OCR-Javanese-Sundane-Script-PWA"

    - name: Executing remote command
      uses: appleboy/ssh-action@alpha.1.0.0
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: npm run build